[package]
name = "day05"
version = "0.1.0"
authors = ["F <fahad.assoumani@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
undup = "0.0.1"
itertools = "0.9.0"
